// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystèmeGestionConsultationPrescriptions.Infrastructure;

#nullable disable

namespace SystèmeGestionConsultationPrescriptions.Infrastructure.Migrations
{
    [DbContext(typeof(SystèmeGestionConsultationPrescriptionsDBContext))]
    [Migration("20241219090831_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SystèmeGestionConsultationPrescriptions.Core.Entities.Consultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnostic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DossierMedicalId")
                        .HasColumnType("int");

                    b.Property<int>("MedecinId")
                        .HasColumnType("int");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DossierMedicalId");

                    b.HasIndex("MedecinId");

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("SystèmeGestionConsultationPrescriptions.Core.Entities.DossierMedical", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdentifiantPatient")
                        .HasColumnType("int");

                    b.Property<string>("TraitementsPassesString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DossiersMedical");
                });

            modelBuilder.Entity("SystèmeGestionConsultationPrescriptions.Core.Entities.Medecin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdresseCourriel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Identifiant")
                        .HasColumnType("int");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroLicence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Medecins");
                });

            modelBuilder.Entity("SystèmeGestionConsultationPrescriptions.Core.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdresseCourriel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DossierMedicalId")
                        .HasColumnType("int");

                    b.Property<int?>("MedecinId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DossierMedicalId");

                    b.HasIndex("MedecinId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("SystèmeGestionConsultationPrescriptions.Core.Entities.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsultationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dosage")
                        .HasColumnType("int");

                    b.Property<int?>("DossierMedicalId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Duree")
                        .HasColumnType("time");

                    b.Property<int>("Etat")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medicament")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId");

                    b.HasIndex("DossierMedicalId");

                    b.HasIndex("PatientId");

                    b.ToTable("Prescription");
                });

            modelBuilder.Entity("SystèmeGestionConsultationPrescriptions.Core.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateConnexion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeconnexion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("SystèmeGestionConsultationPrescriptions.Core.Entities.Consultation", b =>
                {
                    b.HasOne("SystèmeGestionConsultationPrescriptions.Core.Entities.DossierMedical", "DossierMedical")
                        .WithMany("consultations")
                        .HasForeignKey("DossierMedicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystèmeGestionConsultationPrescriptions.Core.Entities.Medecin", "Medecin")
                        .WithMany()
                        .HasForeignKey("MedecinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DossierMedical");

                    b.Navigation("Medecin");
                });

            modelBuilder.Entity("SystèmeGestionConsultationPrescriptions.Core.Entities.Patient", b =>
                {
                    b.HasOne("SystèmeGestionConsultationPrescriptions.Core.Entities.DossierMedical", "DossierMedical")
                        .WithMany()
                        .HasForeignKey("DossierMedicalId");

                    b.HasOne("SystèmeGestionConsultationPrescriptions.Core.Entities.Medecin", "Medecin")
                        .WithMany("Patients")
                        .HasForeignKey("MedecinId");

                    b.Navigation("DossierMedical");

                    b.Navigation("Medecin");
                });

            modelBuilder.Entity("SystèmeGestionConsultationPrescriptions.Core.Entities.Prescription", b =>
                {
                    b.HasOne("SystèmeGestionConsultationPrescriptions.Core.Entities.Consultation", "Consultation")
                        .WithMany("_prescriptions")
                        .HasForeignKey("ConsultationId");

                    b.HasOne("SystèmeGestionConsultationPrescriptions.Core.Entities.DossierMedical", null)
                        .WithMany("traitementActifs")
                        .HasForeignKey("DossierMedicalId");

                    b.HasOne("SystèmeGestionConsultationPrescriptions.Core.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SystèmeGestionConsultationPrescriptions.Core.Entities.Consultation", b =>
                {
                    b.Navigation("_prescriptions");
                });

            modelBuilder.Entity("SystèmeGestionConsultationPrescriptions.Core.Entities.DossierMedical", b =>
                {
                    b.Navigation("consultations");

                    b.Navigation("traitementActifs");
                });

            modelBuilder.Entity("SystèmeGestionConsultationPrescriptions.Core.Entities.Medecin", b =>
                {
                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
