// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystèmeGestionConsultationPrescriptions.Infrastructure;

#nullable disable

namespace SystèmeGestionConsultationPrescriptions.Infrastructure.Migrations
{
    [DbContext(typeof(SystèmeGestionConsultationPrescriptionsDBContext))]
    [Migration("20241219005352_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SystèmeGestionConsultationPrescriptions.Core.Entities.Consultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnostic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DossierMedicalId")
                        .HasColumnType("int");

                    b.Property<string>("Motif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observations")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DossierMedicalId");

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("SystèmeGestionConsultationPrescriptions.Core.Entities.DossierMedical", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdentifiantPatient")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DossiersMedical");
                });

            modelBuilder.Entity("SystèmeGestionConsultationPrescriptions.Core.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdresseCourriel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DossierMedicalId")
                        .HasColumnType("int");

                    b.Property<int>("IdMedecin")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DossierMedicalId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("SystèmeGestionConsultationPrescriptions.Core.Entities.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsultationId")
                        .HasColumnType("int");

                    b.Property<int>("Dosage")
                        .HasColumnType("int");

                    b.Property<int?>("DossierMedicalId")
                        .HasColumnType("int");

                    b.Property<int?>("DossierMedicalId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("Duree")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Etat")
                        .HasColumnType("bit");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medicament")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId");

                    b.HasIndex("DossierMedicalId");

                    b.HasIndex("DossierMedicalId1");

                    b.ToTable("Prescription");
                });

            modelBuilder.Entity("SystèmeGestionConsultationPrescriptions.Core.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateConnexion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeconnexion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdentifiantUtilisateur")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("SystèmeGestionConsultationPrescriptions.Core.Entities.Consultation", b =>
                {
                    b.HasOne("SystèmeGestionConsultationPrescriptions.Core.Entities.DossierMedical", null)
                        .WithMany("Consultations")
                        .HasForeignKey("DossierMedicalId");
                });

            modelBuilder.Entity("SystèmeGestionConsultationPrescriptions.Core.Entities.Patient", b =>
                {
                    b.HasOne("SystèmeGestionConsultationPrescriptions.Core.Entities.DossierMedical", "DossierMedical")
                        .WithMany()
                        .HasForeignKey("DossierMedicalId");

                    b.Navigation("DossierMedical");
                });

            modelBuilder.Entity("SystèmeGestionConsultationPrescriptions.Core.Entities.Prescription", b =>
                {
                    b.HasOne("SystèmeGestionConsultationPrescriptions.Core.Entities.Consultation", "Consultation")
                        .WithMany("Prescriptions")
                        .HasForeignKey("ConsultationId");

                    b.HasOne("SystèmeGestionConsultationPrescriptions.Core.Entities.DossierMedical", null)
                        .WithMany("PrescriptionsActives")
                        .HasForeignKey("DossierMedicalId");

                    b.HasOne("SystèmeGestionConsultationPrescriptions.Core.Entities.DossierMedical", null)
                        .WithMany("PrescriptionsTerminees")
                        .HasForeignKey("DossierMedicalId1");

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("SystèmeGestionConsultationPrescriptions.Core.Entities.Consultation", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("SystèmeGestionConsultationPrescriptions.Core.Entities.DossierMedical", b =>
                {
                    b.Navigation("Consultations");

                    b.Navigation("PrescriptionsActives");

                    b.Navigation("PrescriptionsTerminees");
                });
#pragma warning restore 612, 618
        }
    }
}
